config/routes.rb
Rtopology::Application.routes.draw do
  resources :sites

  root :to => 'sites#index'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :asset_type, :md5, :page_id, :path, :size
  belongs_to :page, :dependent => :destroy
end

app/models/audit.rb
class Audit < ActiveRecord::Base
  attr_accessible :site_id
  belongs_to :site, :dependent => :destroy
  has_many :reports, :dependent => :delete_all
  has_many :pages, :through => :reports

  def complete?
    site.pages.count <= pages.count
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :path, :site_id, :results, :discovered_id, :response_code, :response_time, :last_audited_at, :last_error, :last_error_at, :digest

  belongs_to :site, :dependent => :destroy
  belongs_to :discovered, :class_name => "Page", :foreign_key => "discovered_id"
  has_many :reports, :dependent => :delete_all

  validates_presence_of :path
  validates :path, :uniqueness => { :scope => :site_id, :message => "already scraped" }
  validate :check_for_correct_host, :check_for_slash, :check_not_mailto
  after_validation :format_path

  def check_for_correct_host
    if(URI(path).host != URI(site.url).host && URI(path).host != nil)
      errors.add(:path, "is offsite") 
    end
  rescue 
    errors.add(:path, "can not be processed") 
  end
  
  def check_for_slash 
    if !(URI(path).path.match(/^\//))
      errors.add(:path, "does not start with a slash") 
    end
  rescue
    false
  end

  def check_not_mailto
    if path.match /^mailto:/
      errors.add(:path, "should not be a mailto link") 
    end
  rescue
    false
  end

  def format_path
    path = URI(path.to_s).path
  end

  def as_json options = {}
    { :path => path }
  end

  def page_reports
    audits = []
    audits << OpenStruct.new({ :message => "This page's url is #{path.length} chars. This is a little long." }) unless path.length < 115
    audits
  end

  def uri
    site.uri + path
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :message, :score
  belongs_to :audit, :dependent => :destroy
  belongs_to :page, :dependent => :destroy
  validates :message, :presence => true, :uniqueness => {:scope => :page_id}
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :description, :site_name, :url, :port
  validates_presence_of :site_name, :url, :port
  has_many :pages, :dependent => :delete_all
  has_many :audits, :dependent => :delete_all
  
  def home_page
    Page.find_or_create_by_path("/", :site_id => id)
  end

  def last_audit
    Audit.where(:site_id => id).order("created_at DESC").first
  end

  def uri
    return "#{url}:#{port.to_s}" unless port == 80 
    url 
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
  def page_status_class page
    return "red" if (500..599).include?(page.response_code)
    "green"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    
        <%= stylesheet_link_tag 'application' %>
        <%= yield :head %>

    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <%= yield %>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.0.min.js"><\/script>')</script>
        <% javascript_include_tag 'application' %>
        <%= yield :scripts %>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>

app/views/sites/_form.html.haml
= form_for @site do |f|
  -if @site.errors.any?
    #error_explanation
      %h2= "#{pluralize(@site.errors.count, "error")} prohibited this site from being saved:"
      %ul
        - @site.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :site_name
    = f.text_field :site_name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :port
    = f.text_field :port, :value => 80
  
  .actions
    = f.submit 'Save'

app/views/sites/edit.html.haml
%h1 Editing site

= render 'form'

= link_to 'Show', @site
\|
= link_to 'Back', sites_path

app/views/sites/index.html.haml
%h1 Listing sites

%table
  %tr
    %th Site name
    %th Description
    %th Url
    %th
    %th
    %th

  - @sites.each do |site|
    %tr
      %td= site.site_name
      %td= site.description
      %td= site.url
      %td= link_to 'Show', site
      %td= link_to 'Edit', edit_site_path(site)
      %td= link_to 'Destroy', site, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Site', new_site_path

app/views/sites/new.html.haml
%h1 New site

= render 'form'

= link_to 'Back', sites_path

app/views/sites/show.html.haml
- content_for :head do
  = stylesheet_link_tag 'site_show'

%header
  %h1= @site.site_name
  %h2= @site.description 
  %p= link_to "Visit Site", "#{@site.url}:#{@site.port}"
  %p= link_to 'Edit', edit_site_path(@site)

#pages
  - @site.pages.each do |page|
    .page{ :class => page_status_class(page) }
      .response_code= page.response_code
      = link_to page.path, page.uri
      - if page.response_time
        .response_time #{page.response_time}ms
      %ul.reports
        - page.reports.each do |report|
          %li #{report.message}
        - page.page_reports.each do |report|
          %li #{report.message}